name: Repository Complaint
description: Submit a complaint regarding a repository.
title: "[Complaint] Repository Issue"
labels: ["complaint", "inquiry"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        TIP: If a repository is a fork and clearly violates copyright laws  
        (e.g., uploading confidential documents in full), filing a DMCA  
        without warning is an option.

        Thank you for reaching out.  
        Please provide detailed information regarding your complaint.  
        **Note:** This complaint will be publicly visible.

  - type: input
    id: repository_url
    attributes:
      label: Target Repository URL
      description: Provide the full URL of the repository you are complaining about.
      placeholder: "https://github.com/owner/repository"
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Complaint Details
      description: Briefly explain the issue and its impact. A concise summary is sufficient; detailed evidence is not required.
      placeholder: "Describe the issue and its impact here..."
    validations:
      required: true

  - type: textarea
    id: resolution_preference
    attributes:
      label: Preferred Resolution Method
      description: Specify what action you expect to resolve the complaint (e.g., complete repository removal, making the repository private, modifying/removing specific files, etc.).
      placeholder: "Describe your preferred resolution method..."
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Affiliated Organization
      description: If applicable, specify the organization or company you belong to. (Leave blank if individual.)
      placeholder: "Company/Organization Name"
    validations:
      required: false

  - type: checkboxes
    id: authorization
    attributes:
      label: Authorization Confirmation
      description: Confirm that you have the authority to file this complaint on behalf of the organization.
      options:
        - label: "I confirm that I have the authority to file this complaint on behalf of the stated organization, and this report is not false."
          required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Acknowledgement
      description: Please confirm that your complaint complies with GitHub's Terms of Service.
      options:
        - label: "I confirm that this complaint is appropriate and adheres to GitHub's guidelines."
          required: true

  - type: checkboxes
    id: personal_information
    attributes:
      label: Privacy Agreement
      description: Confirm that no personal information is included in this complaint.
      options:
        - label: "I confirm that no personal information is included in this complaint."
          required: true

  - type: checkboxes
    id: response_permission
    attributes:
      label: Response Permission
      description: Allow responses to your complaint in this repository.
      options:
        - label: "I agree that responses to this complaint may be posted publicly in this repository."
          required: true

  - type: checkboxes
    id: public_acknowledgment
    attributes:
      label: Public Disclosure Agreement
      description: Confirm that you understand and accept that this complaint will be publicly visible.
      options:
        - label: "I agree that this complaint will be publicly visible."
          required: true
